config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy



  get 'home/search', to: 'home#search', as: :home_search
  get 'employees/search', to: 'employees#search', as: :employee_search
  
  get 'stores/:id/payroll', to: 'payrolls#get_store_form', as: :store_form
  get 'payrolls', to: 'payrolls#calculate_stores', as: :calculate_stores

  get 'payrolls/info', to: 'payrolls#info', as: :payroll_info
  get 'payrolls/emp_payroll_info', to: 'payrolls#emp_payroll_info', as: :emp_payroll_info



  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :employees
  resources :stores
  resources :assignments
  resources :users
  resources :sessions
  resources :shifts
  resources :pay_grades
  resources :pay_grade_rates
  resources :jobs
  resources :shift_jobs 


  # Custom routes
  patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment
  patch 'shifts/:id/clockin', to: 'shifts#clockin', as: :clock_in_shift
  patch 'shifts/:id/clockout', to: 'shifts#clockout', as: :clock_out_shift

  # You can have the root of your site routed with 'root'
  root 'home#index'


  get 'employee/edit' => 'employees#edit', :as => :edit_current_user
  get 'signup' => 'employee#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout


end

app/models/employee.rb
class Employee < ApplicationRecord
  include AppHelpers::Validations
  include AppHelpers::Deletions
  include AppHelpers::Activeable::InstanceMethods
  extend AppHelpers::Activeable::ClassMethods
  
  has_secure_password

  # Relationships
  has_many :assignments 
  has_many :stores, through: :assignments
  has_many :shifts, through: :assignments 
  has_many :pay_grades, through: :assignments
  has_many :pay_grade_rates, through: :pay_grades

  # Scopes
  scope :younger_than_18, -> { where('date_of_birth > ?', 18.years.ago.to_date) }
  scope :is_18_or_older,  -> { where('date_of_birth <= ?', 18.years.ago.to_date) }
  scope :regulars,        -> { where('role = ?', 'employee') }
  scope :managers,        -> { where('role = ?', 'manager') }
  scope :admins,          -> { where('role = ?', 'admin') }
  scope :alphabetical,    -> { order('last_name, first_name') }
  scope :search, ->(term) { where('first_name LIKE ? OR last_name LIKE ?', "#{term}%", "#{term}%") }
  # scope :for_store,       ->(store) { joins(:assignments, :store).where("assignments.store_id = ?", store.id)}
  scope :for_store,       ->(store_id) { joins(:assignments).where(assignments: {store_id: store_id, end_date: nil})}


  # Validations
  validates_presence_of :first_name, :last_name, :ssn
  validates_date :date_of_birth, :on_or_before => lambda { 14.years.ago }, on_or_before_message: 'must be at least 14 years old'
  validates_format_of :phone, with: /\A(\d{10}|\(?\d{3}\)?[-. ]\d{3}[-.]\d{4})\z/, message: 'should be 10 digits (area code needed) and delimited with dashes only'
  validates_format_of :ssn, with: /\A\d{3}[- ]?\d{2}[- ]?\d{4}\z/, message: 'should be 9 digits and delimited with dashes only'
  validates_uniqueness_of :ssn
  validates_inclusion_of :role, in: %w[admin manager employee], message: 'is not an option'
  # ... more validations for phase 4 & 5
  validates :username, presence: true, uniqueness: { case_sensitive: false}
  validates_presence_of :role, on: :create
  validates_presence_of :password, on: :create 
  validates_presence_of :password_confirmation, on: :create 
  validates_confirmation_of :password, on: :create, message: 'does not match'
  validates_length_of :password, minimum: 4, message: 'must be at least 4 characters long', allow_blank: true

  # Other methods
  def name
    "#{last_name}, #{first_name}"
  end
  
  def proper_name
    "#{first_name} #{last_name}"
  end

  def over_18?
    date_of_birth.to_date < 18.years.ago.to_date
  end
  
  def age
    (Time.now.to_s(:number).to_i - date_of_birth.to_time.to_s(:number).to_i)/10e9.to_i
  end

  def current_assignment
    curr_assignment = self.assignments.current    
    return nil if curr_assignment.empty?
    curr_assignment.first   # return as a single object, not an array
  end

  # Add in methods for phases 4 & 5 for authentication and payment handling
  include EmployeePayment
  include EmployeeAuthentication

  # Callbacks
  before_save -> { strip_nondigits_from(:phone) }
  before_save -> { strip_nondigits_from(:ssn) }

  # ... additional callbacks in phases 4 & 5
  include EmployeeDeletion
  before_destroy -> { handle_deletion_request() }
  after_rollback -> { handle_deletion_failure() }

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy, :retrieve_employee_payroll, :retrieve_employee_shifts]

  def index
    # for phase 3 only

    if current_user.role?(:admin)
    @active_managers = Employee.managers.active.alphabetical.paginate(page: params[:man_page]).per_page(10)
    @active_employees = Employee.regulars.active.alphabetical.paginate(page: params[:emp_page]).per_page(10)
    @inactive_employees = Employee.inactive.alphabetical.paginate(page: params[:in_page]).per_page(10)
    elsif current_user.role?(:manager)
    @active_managers = Employee.for_store(current_user.current_assignment.store_id).managers.active.alphabetical.paginate(page: params[:page]).per_page(6)
    @active_employees = Employee.regulars.for_store(current_user.current_assignment.store_id).active.alphabetical.paginate(page: params[:page]).per_page(6)
    @inactive_employees = Employee.for_store(current_user.current_assignment.store_id).inactive.alphabetical.paginate(page: params[:page]).per_page(6)
    end

    retrieve_employee_payroll
    # retrieve_employee_shifts
    @stores = Store.all

  end

  def show
    retrieve_employee_assignments
    retrieve_employee_shifts
    retrieve_employee_payroll
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to @employee, notice: "Successfully added #{@employee.proper_name} as an employee."
    else
      render action: 'new'
    end
  end

  def update
    if @employee.update_attributes(employee_params)
      redirect_to @employee, notice: "Updated #{@employee.proper_name}'s information."
    else
      render action: 'edit'
    end
  end


  def destroy

    if @employee.destroy
      @employee.destroy
      respond_to do |format|
        format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      @employee.active == false
      redirect_to @employee, notice: "Cannot destroy an employee who has worked more than one shift. Will be made inactive instead."
    end
  end


    def search
      redirect_back(fallback_location: employee_path) if params[:query].blank?
      @query = params[:query]
      @employees = Employee.search(@query)
      @total_hits = @employees.size 
    end

     def retrieve_employee_shifts

      @upcoming_shifts_in_7 = Shift.upcoming.for_next_days(7).by_store.by_employee.for_employee(current_user).paginate(page: params[:page]).per_page(5)

      if (current_user.role?(:admin)|| current_user.role?(:manager))
        date_range = DateRange.new(7.days.ago.to_date, 7.days.from_now.to_date)
        @past_shifts = Shift.past.by_store.by_employee.for_past_days(7).for_employee(@employee).paginate(page: params[:page]).per_page(5)
        @pending_shifts = Shift.pending.by_store.by_employee.for_dates(date_range).for_employee(@employee).paginate(page: params[:page]).per_page(5)
        @completed_shifts = Shift.completed.by_store.by_employee.for_dates(date_range).for_employee(@employee).paginate(page: params[:page]).per_page(5)
      else
        date_range = DateRange.new(7.days.ago.to_date, 7.days.from_now.to_date)
        @past_shifts = Shift.past.by_store.by_employee.for_past_days(7).for_employee(current_user).paginate(page: params[:page]).per_page(5)
        @pending_shifts = Shift.pending.by_store.by_employee.for_dates(date_range).for_employee(current_user).paginate(page: params[:page]).per_page(5)
        @past_shifts = Shift.past.by_store.by_employee.for_employee(current_user).paginate(page: params[:page]).per_page(5)
        @completed_shifts = Shift.completed.for_employee(current_user).by_employee.paginate(page: params[:page]).per_page(5)
        

      end
      # @past_shifts = Shift.past.by_store.by_employee.for_employee(current_user).paginate(page: params[:page]).per_page(5)
      # @completed_shifts = Shift.completed.for_employee(current_user).by_employee.paginate(page: params[:page]).per_page(5)
      # @pending_shifts = Shift.pending.for_employee(current_user).by_employee.paginate(page: params[:page]).per_page(5)
      if !current_user.current_assignment.nil?
        @finished_shifts_for_manager_store= Shift.finished.for_store(current_user.current_assignment.store).by_employee.paginate(page: params[:page]).per_page(5)
      end


  end

   def retrieve_employee_payroll
     @calculator = PayrollCalculator.new(DateRange.new(7.days.ago.to_date, Date.current.to_date))  
     @seven_days_employee_payroll_record = @calculator.create_payroll_record_for(current_user)

     @calculator2 = PayrollCalculator.new(DateRange.new(14.days.ago.to_date, Date.current.to_date))  
     @half_month_employee_payroll_record = @calculator2.create_payroll_record_for(current_user)

     @calculator3 = PayrollCalculator.new(DateRange.new(1.month.ago.to_date, Date.current.to_date))  
     @monthly_employee_payroll_record = @calculator3.create_payroll_record_for(current_user)
  end

  def retrieve_employees_at_manager_store
      @employees_at_manager_store = Shift.for_store(current_user.current_assignment.store).employees.proper_name
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :ssn, :phone, :date_of_birth, :role, :active, :username, :password, :password_confirmation)
  end

  def retrieve_employee_assignments
    @current_assignment = @employee.current_assignment
    @previous_assignments = @employee.assignments.to_a - [@current_assignment]
  end



 



end

app/helpers/employees_helper.rb
module EmployeesHelper
  def number_to_ssn(num)
    "#{num[0..2]}-#{num[3..4]}-#{num[5..8]}"
  end
end

app/views/employees/_active_employees.html.erb
<%= render partial: 'employee_lists', locals: {employees: @active_employees, state: 'active'} %>

app/views/employees/_detailed_completed_shift_list.html.erb
<% if @completed_shifts.blank? %>
    <p>There are no completed shifts at this time.</p>
<% else %>

  <div class="card">
    <div class="card-content">
      <h5>Completed Shifts For This Assignment</h5>

      <table class="striped highlight">
        <thead>
          <th>Shift ID</th>
          <th>Date</th>
          <th>Duration</th>
        </thead>
        <% @completed_shifts.each do |shift| %>
          <tr >
            <td><%=shift.id%></td>
            <td><%= shift.date.strftime("%-m/%-d/%y")%></td>
            <td><%=shift.duration%> hours</td>
            
          </tr>

          
        <% end %>
      </table>
      <p>These shifts are +/- one week's time.</p>
      <p class="supertiny"></p>
      <br />
    </div>
    
  </div>

<% end %>

app/views/employees/_employee_data.html.erb
<div class="card">
  <div class="card-content">
    <h4><%= @employee.proper_name %></h4>
    <h5><%= @employee.role.capitalize %></h5><br />

    <b>Current Assignment:&nbsp;&nbsp;</b><br>
      <% if @employee.current_assignment.nil? %>
        n/a<br /><br />
      <% else %>

        <%if current_user.role?(:admin)%>
        <%= link_to @employee.current_assignment.store.name, store_path(@employee.current_assignment.store) %><br />
        since <%= @employee.current_assignment.start_date.strftime("%b %-d, %Y") %><br /><br />
        <%else%>
       <%= @employee.current_assignment.store.name%>
        since <%= @employee.current_assignment.start_date.strftime("%b %-d, %Y") %><br /><br />
        <%end%>


      <% end %>

    <b>Phone:&nbsp;&nbsp;</b><br>
      <%= number_to_phone @employee.phone %><br /><br />

    <b>Social Security Number:&nbsp;&nbsp;</b><br>
      <%= number_to_ssn @employee.ssn %><br /><br />

    <b>Date of Birth:&nbsp;&nbsp;</b><br>
      <%= @employee.date_of_birth.to_datetime.strftime("%b %-d, %Y") %><br /><br />


    <b>Active with AMC?&nbsp;&nbsp;</b>
      <%= @employee.active ? "Yes" : "No" %>
      <br>
  </div>
</div>

app/views/employees/_employee_lists.html.erb
<div class="card">
  <div class="card-content">
    <h4><%= state.capitalize %> <%= role.capitalize %> at AMC</h4>

    <% if employees.empty? %>
      <p>There are no <%= state.downcase %> <%= role.downcase %> at this time.</p>
    <% else %>

      <table class="striped highlight">
        <thead>
          <th>Name</th>
          <th>Store</th>
          <th>Current Assignment</th>
          <th>Phone</th>
          

        </thead>
        <% for employee in employees %>
          <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
            <td class='hyperlink'><%= link_to employee.name, employee_path(employee) %></td>
            <td class='hyperlink'><%= employee.current_assignment.nil? ? 'n/a' : link_to(employee.current_assignment.store.name, store_path(employee.current_assignment.store))  %></td>
            <td class='hyperlink'><%= employee.current_assignment.nil? ? 'n/a' : link_to(employee.current_assignment.id, assignment_path(employee.current_assignment))  %></td>
            <td><%= number_to_phone employee.phone %></td>

          <td class="align_center">

          


          <% if can? :edit, :employee %>
          <td>
            <%= link_to(edit_employee_path(employee), class: 'btn-small cyan darken-4') do %>
              &nbsp;Edit&nbsp;
            <% end %>
          </td>
          <% end %>

          <% if current_user.role? :admin %>
          <td>
              
              <%= link_to(employee_path(employee), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }, class: 'btn-small red darken-4') do %>
                &nbsp;Delete&nbsp;

          <% end %>
          </td>
          <% end %>

  
 

          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
      <%= will_paginate employees, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next", :param_name => page %>

    <% end %>

  </div>
</div>

app/views/employees/_employees_at_manager_store.html.erb
<div class="card">
  <div class="card-content">
    

    <% if employees.blank? %>
      <p>There are no employees at your store.</p>
    <% else %>
      <h5>Add upcoming shifts to employees assigned to your store within the next seven days</h5>
      <table class="striped highlight">
        <thead>
          <tr>
            <th>Employee Name</th>
            <th>Add Shift</th>
                       
          </tr>
        </thead>
        <tbody>
          <% employees.each do |employee| %>
            <tr>

            
              <td class='hyperlink'><%= link_to employee.name, employee_path(employee) %></td>
              
              <td><%= link_to(new_shift_path, class: 'btn-small green darken-1') do %>
                        &nbsp;Add Shift&nbsp;</td>
                <%end%>

            </tr>

           

            
        <% end %>
        </tbody>
      </table>
      <p class="supertiny"></p>
      <br />
      
      <%= will_paginate employees, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next"%>
      <br />
   
    <% end %>
  </div>
</div>

app/views/employees/_inactive_employees.html.erb
<%= render partial: 'employee_lists', locals: {employees: @inactive_employees, state: 'inactive', role: 'employees', page: 'in_page'} %>

app/views/employees/_manager_finished_employee_shifts_list.html.erb
<div class="card">
  <div class="card-content">
    

    <% if shifts.blank? %>
      <p>There are no <%= state.downcase %> shifts at this time.</p>
    <% else %>
      <h5>Write notes for your employee's finished shifts!</h5>
      <table class="striped highlight">
        <thead>
          <tr>
            <th>Employee Name</th>
            <th>Store Name</th>
            <th>Date</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Shift Notes</th>
                       
          </tr>
        </thead>
        <tbody>
          <% shifts.each do |shift| %>
            <tr>

            
              <td class='hyperlink'><%= link_to shift.employee.name, employee_path(shift.assignment.employee) %></td>
              <td class='hyperlink'><%= link_to shift.assignment.store.name, store_path(shift.assignment.store) %></td>
              <td><%= shift.date.strftime("%-m/%-d/%y")%></td>
              <td><%=shift.start_time.strftime("%I:%M %p")%></td>
              <td><%=shift.end_time.strftime("%I:%M %p")%></td>
                

              <td>
                <ul class="collapsible">
                  <li>
                    <div class="collapsible-header"><i class="material-icons">edit</i>Edit</div>
                    <div class="collapsible-body">
                      
                        <%= simple_form_for(shift) do |f| %>
                          <%= f.error_notification %>
                          <div class="row">
                            <div class="form-inputs">
                              <%= f.input :notes, label_html: { class: 'active' } %>
                          </div>

                          <div class="row">
                            <div class="form-actions col s9">
                              <%= f.button :submit, "Update Note" %>
                            </div>
                          </div>
                          <%end%>



                    </div>
                  </li>
                  
                </ul>
              </td>

                  

            </tr>

           

            
        <% end %>
        </tbody>
      </table>
      <p class="supertiny"></p>
      <br />
      
      <%= will_paginate shifts, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
      <br />
   
    <% end %>
  </div>
</div>

app/views/employees/_no_show_employee_shifts_list.html.erb
<div class="card">
  <div class="card-content">
    <h5>No Show Shifts at <%=shifts[0].assignment.store.name%></h5>

    <% if shifts.blank? %>
      <p>There are no <%= state.downcase %> shifts at this time.</p>
    <% else %>

      <table class="striped highlight">
        <thead>
          <tr>
            <th>Shift ID</th>
            <th>Employee Name</th>
            <th>Date</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Reason for No-Show?</th>
            <th>Call this Worker!</th>
                       
          </tr>
        </thead>
        <tbody>
          <% shifts.each do |shift| %>
            <tr>

              <td><%= shift.id%></td>
              <td class='hyperlink'><%= link_to shift.employee.name, employee_path(shift.assignment.employee) %></td>
              <td><%= shift.date.strftime("%-m/%-d/%y")%></td>
              <td><%=shift.start_time.strftime("%I:%M %p")%></td>
              <td><%=shift.end_time.strftime("%I:%M %p")%></td>
                


              <td>
                <ul class="collapsible">
                  <li>
                    <div class="collapsible-header"><i class="material-icons">edit</i>Edit</div>
                    <div class="collapsible-body">
                      
                        <%= simple_form_for(shift) do |f| %>
                          <%= f.error_notification %>
                          <div class="row">
                            <div class='note-form'>
                            <div class="form-inputs">
                              <%= f.input :notes, label_html: { class: 'active' } %>
                          </div>
                          </div>

                          <div class="row">
                            <div class="form-actions col s9">
                              <%= f.button :submit, "Update Note" %>
                            </div>
                          </div>
                          <%end%>

                    </div>
                  </li>
                  
                </ul>
              </td>
              </td>

              <td>
                  <%=shift.assignment.employee.phone%>
              
                
              </td>

              <td>
                      
                      <%= link_to(shift_path(shift), class: 'btn-small black darken-1') do %>
                        &nbsp;View Shift &nbsp;

                  <% end %>


                 
                  </td>
           

                  <!--  -->
                       

               
            </tr>

           

            
        <% end %>
        </tbody>
      </table>
      <p class="supertiny"></p>
      <br />
      
      <%= will_paginate shifts, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next"%>
      <br />
   
    <% end %>
  </div>
</div>

app/views/employees/_shift_history.html.erb
<ul id="tabs-swipe-demo" class="tabs">
    <li class="tab col s5"><a href="#test-swipe-1">Pending</a></li>
   
    <li class="tab col s5"><a class="active" href="#test-swipe-2">Completed</a></li>
    
  </ul>
  <div id="test-swipe-1">  <%= render :partial => "detailed_pending_shift_list" %></div>
  
  <div id="test-swipe-2"><%= render :partial => "detailed_completed_shift_list" %></div>

  


 

app/views/employees/_stores_with_no_shows.html.erb
<div class="card">
  <div class="card-content">
    

    <h4>Number of Employees per Store that Didn't Show Up to Shift</h4>
      
      <table class="striped highlight">
        <thead>
          <tr>
            <th>Store Name</th>
            <th>Number of Employees</th>
            <th>Call this Store!</th>
                       
          </tr>
        </thead>
        <tbody>
          <% stores.each do |store| %>
            <tr>

            
              <td class='hyperlink'><%= link_to store.name, store_path(store) %></td>

              <td><%=store.shifts.pending.past.count%></td>
              <td><%=store.phone%></td>
            </tr>

           

            
        <% end %>
        </tbody>
      </table>
      <p class="supertiny"></p>
      <br />
      
      <%= will_paginate stores, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
      <br />
   
  
  </div>
</div>

app/views/employees/_tabbed_index_for_admin_dashboard.html.erb
<%= render :partial => "partials/title_with_search", locals: {title: "Employees at AMC"} %>

  <div class="card gray lighten-1">
    <div class="card-content">
      <div class='card-top'>
        <h3><%=current_user.proper_name%>'s Dashboard</h3>
      <p>Use this dashboard to see no shifts and calculate payroll</p>
      </div>
      
         
     
    
    
     
    </div>
    <div class="card-tabs">
      <ul class="tabs tabs-fixed-width">
        <li class="tab"><a class='active'href="#test5">Store Payroll Calculator</a></li>
        <li class="tab"><a href="#test7">Stores with No-Shows</a></li>
      </ul>
    </div>
    <div class="card-content gray lighten-4">
      <div id="test5"><%= render :partial => "stores/store_lists", locals: {stores: @stores, state: 'Active'}%></div>
      <div id="test7"><%= render :partial => "employees/stores_with_no_shows",  locals: {stores: @no_show_stores, state: 'finished'}%></div>
    </div>
  </div>

app/views/employees/_tabbed_index_for_employee_dash.html.erb
<div id='tabbed'>
  <h4><%=current_user.proper_name%>'s Dashboard</h4>
  <div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s3"><a href="#test3">Today's Shifts</a></li>
      	<li class="tab col s3"><a href="#test1">Upcoming Shifts</a></li>
        <li class="tab col s3"><a href="#test2">All Past Shifts</a></li>
        

        
        
        
      </ul>
    </div>
    <div id="test3" class="col s12"><%= render :partial => "shifts/special_employee_shift_clock_view", locals: {shifts: @pending_shifts_for_today, state: "Pending", can_clock: true }%> </div>
    <div id="test1" class="col s12"><%= render :partial => "shifts/special_employee_shift_clock_view", locals: {shifts: @upcoming_shifts_in_7, state: "Upcoming", can_clock: false }%> </div>
    <div id="test2" class="col s12"><%= render :partial => "shifts/shifts_lists", locals: {shifts: @past_shifts, state: "Past", can_clock: false, is_past: false}%> </div>

 
	</div>



  
   
    
</div>



<%= link_to(employee_path(current_user), class: 'btn-small yellow darken-3') do %>
                        &nbsp;View Employee Information &nbsp;

                  <% end %>

app/views/employees/edit.html.erb
<%= render partial: 'partials/form_structure', locals: {object: @employee, 
                                                        type_of_form: 'Employee',
                                                        fields: 'fields'} %>

app/views/employees/index.html.erb
<% if current_user.role?(:admin) || current_user.role?(:manager) %>
	<%= render partial: 'tabbed_index' %>
	
          
<% else %>
	<%= render partial: 'employee_dashboard' %>
<% end %>





                                                       