config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy



  get 'home/search', to: 'home#search', as: :home_search
  get 'employees/search', to: 'employees#search', as: :employee_search
  
  get 'stores/:id/payroll', to: 'payrolls#get_store_form', as: :store_form
  get 'payrolls', to: 'payrolls#calculate_stores', as: :calculate_stores

  get 'payrolls/info', to: 'payrolls#info', as: :payroll_info
  get 'payrolls/emp_payroll_info', to: 'payrolls#emp_payroll_info', as: :emp_payroll_info



  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :employees
  resources :stores
  resources :assignments
  resources :users
  resources :sessions
  resources :shifts
  resources :pay_grades
  resources :pay_grade_rates
  resources :jobs
  resources :shift_jobs 


  # Custom routes
  patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment
  patch 'shifts/:id/clockin', to: 'shifts#clockin', as: :clock_in_shift
  patch 'shifts/:id/clockout', to: 'shifts#clockout', as: :clock_out_shift

  # You can have the root of your site routed with 'root'
  root 'home#index'


  get 'employee/edit' => 'employees#edit', :as => :edit_current_user
  get 'signup' => 'employee#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout


end

app/models/assignment.rb
class Assignment < ApplicationRecord
  include AppHelpers::Validations
  include AppHelpers::Deletions

  # Relationships
  belongs_to :store
  belongs_to :employee
  belongs_to :pay_grade
  has_many :shifts 
  
  # Scopes
  scope :current,       -> { where('end_date IS NULL') }
  scope :past,          -> { where('end_date IS NOT NULL') }
  scope :by_store,      -> { joins(:store).order('name') }
  scope :by_employee,   -> { joins(:employee).order('last_name, first_name') }
  scope :chronological, -> { order(Arel.sql('start_date DESC, end_date IS NOT NULL, end_date DESC')) }
  scope :for_store,     ->(store) { where("store_id = ?", store.id) }
  scope :for_employee,  ->(employee) { where("employee_id = ?", employee.id) }
  scope :for_pay_grade, ->(pay_grade) { where("pay_grade_id = ?", pay_grade.id) }
  scope :for_role,      ->(role) { joins(:employee).where("role = ?", role) }
  scope :for_date,      ->(date) { where("start_date <= ? AND (end_date > ? OR end_date IS NULL)", date, date) }

  # Validations
  validates_presence_of :store_id, :employee_id, :pay_grade_id, :start_date
  validates_date :start_date, on_or_before: ->{ Date.current }, on_or_before_message: "cannot be in the future"
  validates_date :end_date, after: :start_date, on_or_before: ->{ Date.current }, allow_blank: true
  validate ->{ is_active_in_system(:employee) }
  validate ->{ is_active_in_system(:store) }
  validate ->{ is_active_in_system(:pay_grade) }  # phase 4 & 5 only

  # Other methods
  def terminate
    return false unless self.end_date.nil?
    self.start_date = Date.current
    end_previous_assignment
    remove_pending_shifts
    self.reload
  end

  # Callbacks
  before_create :end_previous_assignment

  # ... for phase 4 & 5 only
  before_destroy do
    verify_no_pending_shifts
    if errors.present?
      throw(:abort)
    else
      remove_pending_shifts
    end
  end

  private
  def end_previous_assignment
    current_assignment = Employee.find(self.employee_id).current_assignment
    if current_assignment.nil?
      return true 
    else
      current_assignment.update_attribute(:end_date, self.start_date.to_date)
    end
  end

  def verify_no_pending_shifts
    unless self.shifts.started.empty? && self.shifts.finished.empty?
      errors.add(:base, "This assignments is associated with worked shifts and cannot be deleted.")
    end
  end

  def remove_pending_shifts
    self.shifts.pending.each { |s| s.destroy }
  end
  
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :terminate, :destroy]

  # def index
  #   # for phase 3 only
  #     @current_assignments = Assignment.current.chronological.paginate(page: params[:page]).per_page(10)
  #     @past_assignments = Assignment.past.chronological.paginate(page: params[:page]).per_page(10)
  # end

  def index
      if current_user.role? :admin
        @current_assignments = Assignment.current.by_store.by_employee.chronological.paginate(page: params[:page]).per_page(6)
        @past_assignments = Assignment.past.by_store.by_employee.chronological.paginate(page: params[:page]).per_page(6)
      else current_user.role? :manager
        @current_assignments = Assignment.current.for_store(current_user.current_assignment.store).by_employee.chronological.paginate(page: params[:page]).per_page(6)
        @past_assignments = Assignment.past.for_store(current_user.current_assignment.store).by_employee.paginate(page: params[:page]).per_page(6)  
      end
  end

  def get_assignment_shifts
      @completed_shifts = Shift.completed.by_store.by_employee.paginate(page: params[:page]).per_page(5)
      @pending_shifts = Shift.pending.by_store.by_employee.paginate(page: params[:page]).per_page(5)
  end


  def new
    @assignment = Assignment.new
    @assignment.employee_id = params[:employee_id] unless params[:employee_id].nil?
  end

  def create
    @assignment = Assignment.new(assignment_params)
    if @assignment.save
      redirect_to assignments_path, notice: "Successfully added the assignment."
    else
      render action: 'new'
    end
  end

  def show
    get_assignment_shifts
  end

  def edit
  end

   def update
    if @assignment.update_attributes(assignment_params)
      redirect_to @assignment, notice: "Updated #{@assignment.employee.proper_name}'s assignment."
    else
      render action: 'edit'
    end
  end


  def terminate
    if @assignment.terminate
      redirect_to assignments_path, notice: "Assignment for #{@assignment.employee.proper_name} terminated."
    end
  end

  def destroy
    @assignment.destroy
    redirect_to assignments_path, notice: "Removed assignment from the system."
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_assignment
    @assignment = Assignment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def assignment_params
    params.require(:assignment).permit(:store_id, :employee_id, :start_date, :pay_grade_id)
  end

end

app/helpers/assignments_helper.rb
module AssignmentsHelper
	
	def get_assignment_options

		Assignment.current.by_store.by_employee.chronological.map{|a| ["#{a.employee.name} @ #{a.store.name}", a.id]}
	end
end



    

app/views/assignments/_assignment_data.html.erb
<div class="card">
  <div class="card-content">
    <h4>Assignment <%= @assignment.id %> for <%= @assignment.employee.proper_name%></h4>

    <b>Current Assignment:&nbsp;&nbsp;</b><br>
      <% if @assignment.nil? %>
        n/a<br /><br />
      <% else %>
        <%= link_to @assignment.store.name, store_path(@assignment.store) %><br />
        since <%= @assignment.start_date.strftime("%b %-d, %Y") %><br /><br />
        <p>Assignment Start Date: <%=@assignment.start_date%></p>
        <%if @assignment.end_date == nil %>
        <p>Assignment End Date: n/a</p>
        <%else%>
          <p>Assignment End Date: <%=@assignment.end_date%></p>
        <%end%>

      <% end %>

    
      <br>
  </div>
</div>

app/views/assignments/_assignments_list.html.erb
<div class="card">
  <div class="card-content">
    <h5><%= state.capitalize %> Assignments</h5>

    <% if assignments.empty? %>
      <p>There are no <%= state.downcase %> assignments at this time.</p>
    <% else %>

      <table class="striped highlight">
        <thead>

          <th>Employee Name</th>
          <th>Store Name</th>
          <th>Dates</th>
         
        </thead>
        <% assignments.each do |assignment| %>
          <tr>
            <td class='hyperlink'><%= link_to assignment.employee.name, employee_path(assignment.employee) %></td>
            <td class='hyperlink'><%= link_to assignment.store.name, store_path(assignment.store) %></td>
            <td><%= assignment.start_date.strftime("%-m/%-d/%y") %> - <%= assignment.end_date.nil? ? 'Present' : assignment.end_date.strftime("%-m/%-d/%y") %></td>

            <td>   
                      <%= link_to(assignment_path(assignment), class: 'btn-small black darken-1') do %>
                        &nbsp;View Assignment &nbsp;

                  <% end %>


                 
                  </td>
           


               
                  <td>
                    <%= link_to(edit_assignment_path(assignment), class: 'btn-small cyan darken-4') do %>
                      &nbsp;Edit&nbsp;
                    <% end %>
                  </td>
             

               <% if current_user.role?(:admin) %>
                  <td>
              
              <%= link_to(assignment_path(assignment), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }, class: 'btn-small red darken-4') do %>

                &nbsp;Delete&nbsp;
                <% end %>
                
                 </td>
              <% end %>
             



              <td>
                <% if state.downcase == 'current' and current_user.role? :admin %>
                <%= link_to(terminate_assignment_path(assignment), method: :patch, data: { confirm: 'Are you sure you wish to terminate this assignment?'}, class: 'btn-small orange darken-1') do %>
                  &nbsp;Terminate&nbsp;
                <% end %>
                <% end %>
              </td>


          </td>
           
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
      <%= will_paginate assignments, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
      <br />
    <% end %>
  </div>
</div>

app/views/assignments/_current_assignments.html.erb
<%= render partial: 'assignments_list', locals: { state: 'Current', 
                                                  assignments: @current_assignments } %>

app/views/assignments/_fields.html.erb
<%= f.input :employee_id, collection: Employee.alphabetical.active.to_a, include_blank: true %>
<%= f.input :store_id, collection: Store.alphabetical.active.to_a, include_blank: true %>
<%= f.input :start_date, label_html: { class: 'active' } %>
<%= f.input :pay_grade_id, collection: get_pay_grade_options, include_blank: true %>

app/views/assignments/_past_assignments.html.erb
<%= render partial: 'assignments_list', locals: { state: 'Past', 
assignments: @past_assignments } %>

app/views/assignments/_shift_history.html.erb
<ul id="tabs-swipe-demo" class="tabs">

    <li class="tab col s5"><a href="#test-swipe-1">Pending</a></li>
   
    <li class="tab col s5"><a class="active" href="#test-swipe-2">Completed</a></li>
    
  </ul>
  <div id="test-swipe-1">  <%= render :partial => "employees/detailed_pending_shift_list" %></div>
  
  <div id="test-swipe-2"><%= render :partial => "employees/detailed_completed_shift_list" %></div>

  

 <%= render :partial => 'partials/add_new_object', locals: {model_name: 'shift'} %>

app/views/assignments/_tabbed_index.html.erb
<div id='tabbed'>
  <div class="row">
    <div class="col s12">
      <ul class="tabs">
      	<li class="tab col s3"><a href="#test1">Current Assignments</a></li>
        <li class="tab col s3"><a href="#test2">Past Assignments</a></li>
        
        
      </ul>
    </div>
    <div id="test1" class="col s12"><%= render :partial => "current_assignments" %> </div>
    <div id="test2" class="col s12"><%= render :partial => "past_assignments" %> </div>
    
	</div>
   
    
 

</div>




<% if current_user.role?(:admin)%>
	<%= render :partial => "partials/add_new_object", locals: {model_name: 'assignment'} %>
<% end %>

app/views/assignments/edit.html.erb
<% if can? :edit, :assignment %>
	<%= render partial: 'partials/form_structure', locals: {object: @assignment, 
                                                        type_of_form: 'Assignment',
                                                        fields: 'fields'} %>
          
<% else %>
	You are an employee or a manager. Cannot edit an assignment man. 
<% end %>

app/views/assignments/index.html.erb
<%= render partial: 'tabbed_index' %>

<% if current_user.role? :admin || if current_user.role? :manager %>

	<%= render partial: 'tabbed_index' %>
<%end%>
<%end%>

app/views/assignments/new.html.erb
<%= render partial: 'partials/form_structure', locals: {object: @assignment, 
                                                        type_of_form: 'New Assignment',
                                                        fields: 'fields'} %>

app/views/assignments/show.html.erb
<% if current_user.role?(:admin) || current_user.role?(:manager)%>


<%= render partial: 'partials/show_structure', locals: {model_name: 'assignment', 
                                                         object: @assignment,
                                                         primary: 'assignment_data', 
                                                         secondary: nil,
                                                         sidebar: 'shift_history',
                                                     	 sidebar2: nil} %>






<% end %>