config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy



  get 'home/search', to: 'home#search', as: :home_search
  get 'employees/search', to: 'employees#search', as: :employee_search
  
  get 'stores/:id/payroll', to: 'payrolls#get_store_form', as: :store_form
  get 'payrolls', to: 'payrolls#calculate_stores', as: :calculate_stores

  get 'payrolls/info', to: 'payrolls#info', as: :payroll_info
  get 'payrolls/emp_payroll_info', to: 'payrolls#emp_payroll_info', as: :emp_payroll_info



  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :employees
  resources :stores
  resources :assignments
  resources :users
  resources :sessions
  resources :shifts
  resources :pay_grades
  resources :pay_grade_rates
  resources :jobs
  resources :shift_jobs 


  # Custom routes
  patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment
  patch 'shifts/:id/clockin', to: 'shifts#clockin', as: :clock_in_shift
  patch 'shifts/:id/clockout', to: 'shifts#clockout', as: :clock_out_shift

  # You can have the root of your site routed with 'root'
  root 'home#index'


  get 'employee/edit' => 'employees#edit', :as => :edit_current_user
  get 'signup' => 'employee#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout


end

app/views/partials/_add_new_object.html.erb
<!-- Add a button for new instances of object -->

<% if can? :new, eval(model_name.capitalize) %>
  <%= link_to(eval("new_#{model_name}_path"), class: "waves-effect waves-light btn") do %>
    <strong>Add a New <%= model_name.capitalize %></strong>
  
<% end %>
<% end %>

app/views/partials/_display_base_errors.html.erb
<% unless object.errors.empty? %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box warning">
    <%= object.errors[:base].first %>
  </div>
<% end %>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %>">
    <%= msg %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

<div id="footer" class="center-align">
  
  <%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'About A&M Creamery', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Contact Us', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Privacy Policy', privacy_path %>
  <br />
  <div id="copy">
    Webmaster: <%= mail_to("mfang1@cmu.edu", "Jesus Loving Webmaster", encode: "javascript") %> 
    &nbsp;&nbsp;&copyright 2020
  </div>

</div>

app/views/partials/_form_structure.html.erb
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span>
        <%= simple_form_for(object) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "#{fields}", locals: { f: f } %>
          </div>
        </div>
      </div>
    </div>
      <div class="row">
        <div class="form-actions col s9">
          <%= f.button :submit %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to 'Back', :back %>

app/views/partials/_guest_dashboard.html.erb
<div class='row'>
	<h3 id='home-title'>Welcome to the A&M Creamery, the most badass human resource system you will ever use.</h3>
	<%= image_tag 'dramatic_walking.jpg', class: 'dramatic' %>
</div>

app/views/partials/_index_structure.html.erb
<div class="row">
  <div class="medium-10 columns">
    <!-- primary partial gets displayed here in main div -->

    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>

  

    
   
    
  </div>
  <div class="medium-2 columns">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>



<!-- Add a button for new instances of object -->
<%= render :partial => 'partials/add_new_object', locals: {model_name: model_name} %>

app/views/partials/_nav.html.erb
<nav id="nav">
  <div class="container">
    <ul class="left hide-on-med-and-down">
      <% if current_user.role?(:admin)%>
      <li><%= link_to 'Stores', stores_path %></li>
      <%end%>
      <% if current_user.role?(:admin) || current_user.role?(:manager)%>
      <li><%= link_to 'Employees', employees_path %></li>
      <%end%>

     <!--  <% if can? :read, :assignment %>
          <%= link_to 'Assignments', assignments_path%>
          
      <% end %> -->


      <% if current_user.role?(:admin) || current_user.role?(:manager)%>
        <li><%= link_to 'Assignments', assignments_path %></li>
      <% end %>
      

      
         
      


      <% if current_user.role?(:admin)%>
          <li><%= link_to 'Pay Grades', pay_grades_path %></li>
      <%end%>



      <% if current_user.role?(:admin) || current_user.role?(:manager)%>
          <li><%= link_to 'Jobs', jobs_path %></li>
      <%end%>

      <% if current_user.role?(:manager)%>
          <li><%= link_to 'Payrolls', payroll_info_path %></li>
      <%end%>

      



      <ul id="dropdown2" class="dropdown-content">

            <% if current_user.role?(:admin)%>
              <li><%= link_to "View All Shifts", shifts_path(@all_shifts) %></li>
            <%end%>
            <% if current_user.role?(:manager)%>
            <li><%= link_to "View My Store Shifts", shifts_path %></li>
            <%end%>
             <% if current_user.role?(:admin) || current_user.role?(:manager)%>
              <li><%= link_to "Add A Shift", new_shift_path %></li>
            <%end%>
             <% if current_user.role?(:employee)%>
                <%= link_to "view shifts", shifts_path %>
             <%end%>
          </ul>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Shifts<i class="material-icons right">arrow_drop_down</i></a></li>
     

      <% if current_user.role?(:employee)%>
          <li><%= link_to 'Payrolls', emp_payroll_info_path %></li>
      <%end%>

    </ul>


   


    <ul class="right">
      <li><%= link_to 'Logout', logout_path %></li>
    </ul>

    
    </ul>
  </div>
</nav>

app/views/partials/_nav_guest.html.erb
<nav id="nav">
  <div class="container">
  	<ul class="left hide-on-med-and-down">
  		<li><%= link_to 'Home', home_path %></li>
  		<li><%= link_to 'About Us', about_path %></li>
  		<li><%= link_to 'Contact Us', contact_path %></li>


  	</ul>


	<ul class="right">
		<li><%= link_to 'Login', login_path %></li>
	</ul>

  </div>
</nav>

app/views/partials/_object_options.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

<div class="form-actions">
    <%= link_to(eval("#{model_name.pluralize}_path"), class: 'waves-effect waves-light btn') do %>
      &nbsp;Display All <%# model_name.pluralize.capitalize %>
    <% end %>
    &nbsp;&nbsp;
  
  <% if controller.respond_to?(:update) %>
    <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'waves-effect waves-light btn') do %>
        &nbsp;<%= "Edit #{opt}" %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>
  <br><br>
  <% if controller.respond_to?(:destroy) %>
    <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
        &nbsp;<%= "Delete #{opt}" %>
    <% end %>
  <% end %>

</div>

app/views/partials/_show_object.html.erb
	<%= link_to(eval("#{model_name}_path(object)"), class: "waves-effect waves-light btn") do %>
	<strong>View <%= model_name.capitalize %> Information</strong>
<% end %>

app/views/partials/_show_structure.html.erb
<div class="row">
  <div class="col s6">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <br>
    <% if current_user.role?(:admin) || current_user.role?(:manager)%>
    <%= render :partial => 'partials/display_base_errors', locals: {object: object} %>

    <%= render :partial => 'partials/object_options', locals: {model_name: model_name, object: object} %>
    <%end%>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
  </div>
  <div class="col s6">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
     <%= render partial: "#{sidebar2}" unless sidebar2.blank? %>
  </div>

</div>

app/views/partials/_title_with_search.html.erb
  <div class="row">
    <div class="col s7 right-align">
 
    <i class="medium material-icons">search</i>
    </div>
    <div class="col s5">

             <%= form_with url: home_search_path, method: :get, class: "form-inline", id: "search" do %>

              <%= text_field_tag 'query', '', placeholder:  "Search for Employee (i.e. Alex...)" %>

              <!-- submitting via js (press enter) so not using... -->
              <%# submit_tag('Find') %>
            
          <% end %>



    </div>
  </div>
  

app/views/partials/_topbar.html.erb
<div class="row valign-wrapper" id="topbar">
  <div class="col s1">
    <%# link_to(image_tag('logos/logo_v2_80x80.png'), home_path) %>
  </div>
  <div class="col s10">
    <h2><%= link_to 'A&M Creamery', home_path %></h2>
  </div>
  <div class="col s1">
    &nbsp;
  </div>
</div>