config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy



  get 'home/search', to: 'home#search', as: :home_search
  get 'employees/search', to: 'employees#search', as: :employee_search
  
  get 'stores/:id/payroll', to: 'payrolls#get_store_form', as: :store_form
  get 'payrolls', to: 'payrolls#calculate_stores', as: :calculate_stores

  get 'payrolls/info', to: 'payrolls#info', as: :payroll_info
  get 'payrolls/emp_payroll_info', to: 'payrolls#emp_payroll_info', as: :emp_payroll_info



  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :employees
  resources :stores
  resources :assignments
  resources :users
  resources :sessions
  resources :shifts
  resources :pay_grades
  resources :pay_grade_rates
  resources :jobs
  resources :shift_jobs 


  # Custom routes
  patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment
  patch 'shifts/:id/clockin', to: 'shifts#clockin', as: :clock_in_shift
  patch 'shifts/:id/clockout', to: 'shifts#clockout', as: :clock_out_shift

  # You can have the root of your site routed with 'root'
  root 'home#index'


  get 'employee/edit' => 'employees#edit', :as => :edit_current_user
  get 'signup' => 'employee#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout


end

app/models/shift.rb
class Shift < ApplicationRecord
  include AppHelpers::Validations
  include AppHelpers::Deletions

  # Relationships
  belongs_to :assignment
  has_one :employee, through: :assignment
  has_one :store, through: :assignment
  has_many :shift_jobs #, dependent: :destroy
  has_many :jobs, through: :shift_jobs

  # Scopes
  scope :completed,     -> { joins(:shift_jobs).group(:shift_id) }
  scope :incomplete,    -> { joins("LEFT JOIN shift_jobs ON shifts.id = shift_jobs.shift_id").where('shift_jobs.job_id IS NULL') }
  # alternative ways of finding 'incomplete' scope:
  # scope :incomplete,  -> { where('id NOT IN (?)', Shift.completed.map(&:id)) }
  # also see the class method 'not_completed' further on down...
  scope :for_store,     ->(store) { joins(:assignment, :store).where("assignments.store_id = ?", store.id) }
  scope :for_employee,  ->(employee) { joins(:assignment, :employee).where("assignments.employee_id = ?", employee.id) }
  scope :past,          -> { where('date < ?', Date.current) }
  scope :upcoming,      -> { where('date >= ?', Date.current) }
  scope :pending,       -> { where('status = ?', 'pending') }
  scope :started,       -> { where('status = ?', 'started') }
  scope :finished,      -> { where('status = ?', 'finished') }
  scope :for_next_days, ->(x) { where('date BETWEEN ? AND ?', Date.current, x.days.from_now.to_date) }
  scope :for_past_days, ->(x) { where('date BETWEEN ? AND ?', x.days.ago.to_date, 1.day.ago.to_date) }
  scope :chronological, -> { order(:date, :start_time) }
  scope :by_store,      -> { joins(:assignment, :store).order(:name) }
  scope :by_employee,   -> { joins(:assignment, :employee).order(:last_name, :first_name) }
  scope :by_id, -> {order(:id)}
  # scope not in phase 4 requirements (b/c uses date range object)
  scope :for_dates,     ->(date_range) { where('date BETWEEN ? AND ?', date_range.start_date, date_range.end_date) }


  # Validations
  validates_date :date, on_or_after: lambda { :assignment_starts }, on_or_after_message: "must be on or after the start of the assignment"
  validates_time :start_time #, between: [Time.local(2000,1,1,11,0,0), Time.local(2000,1,1,23,0,0)]
  validates_time :end_time, after: :start_time, allow_blank: true
  validates_inclusion_of :status, in: %w[pending started finished], message: "is not an option"
  validate :assignment_must_be_current, on: :create
  validates_presence_of :assignment_id

  # Other methods
  def report_completed?
    self.shift_jobs.count > 0
  end
  
  # method uses the date_time_helpers gem; https://github.com/profh/time_date_helpers
  def duration
    (round_minutes(self.end_time) - round_minutes(self.start_time, direction: :down))/3600.0
  end
  
  # Callbacks
  # set default end_time (on create only)
  before_create :set_shift_end_time

  # allow shifts to only be deleted if status is 'pending'
  before_destroy do
    verify_shift_is_pending
    if errors.present?
      throw(:abort)
    end
  end

  # Misc Constants
  STATUS_LIST = [['Pending', 'pending'],['Started', 'started'],['Finished', 'finished']].freeze


  private
  def assignment_starts
    @assignment_starts = self.assignment.start_date.to_date
  end
  
  def assignment_must_be_current
    return true if self.assignment.nil?
    unless self.assignment.end_date.nil?
      errors.add(:assignment_id, "is not a current assignment at the creamery")
    end
  end
  
  def set_shift_end_time
    return true unless self.end_time.nil? 
    self.end_time = self.start_time + (3*60*60)
  end

  def verify_shift_is_pending
    unless self.status == 'pending'
      errors.add(:base, "This shift either has begun or has finished and cannot be deleted.")
    end
  end
  
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: [:show, :edit, :update, :destroy, :clockin, :clockout, :get_current_jobs_for_shift]

  # GET /shifts
  # GET /shifts.json
  def index
    
    @fourteen_day_range = DateRange.new(1.week.ago.to_date, 1.week.from_now.to_date)
    if current_user.role? :admin
      @all_shifts = Shift.all.paginate(page: params[:page]).per_page(5)
      @upcoming_shifts = Shift.upcoming.for_dates(@fourteen_day_range).by_store.chronological.by_employee.paginate(page: params[:page]).per_page(5)
      @past_shifts = Shift.past.completed.for_dates(@fourteen_day_range).by_store.by_employee.chronological.paginate(page: params[:page]).per_page(5)
      @completed_shifts = Shift.completed.by_store.by_employee.chronological.paginate(page: params[:page]).per_page(5)
      @pending_shifts = Shift.pending.by_store.by_employee.chronological.paginate(page: params[:page]).per_page(5)

    elsif current_user.role? :manager
      @all_shifts = Shift.all.paginate(page: params[:page]).per_page(10)
      @upcoming_shifts = Shift.upcoming.for_store(current_user.current_assignment.store).chronological.by_employee.paginate(page: params[:page]).per_page(5)
      @past_shifts = Shift.past.finished.for_store(current_user.current_assignment.store).chronological.by_employee.paginate(page: params[:page]).per_page(5)
      @completed_shifts = Shift.completed.for_past_days(7).by_store.by_employee.chronological.paginate(page: params[:page]).per_page(5)
      @pending_shifts = Shift.pending.for_next_days(7).by_store.by_employee.chronological.paginate(page: params[:page]).per_page(5)
    elsif current_user.role? :employee
      #upcoming shifts for next 7 days 
      @upcoming_shifts  = Shift.upcoming.for_employee(current_user).chronological.paginate(page: params[:page]).per_page(8)
      @past_shifts = Shift.past.for_employee(current_user).by_employee.chronological.paginate(page: params[:page]).per_page(8)
      @completed_shifts = Shift.completed.for_employee(current_user).chronological.by_employee.paginate(page: params[:page]).per_page(5)
      @pending_shifts = Shift.pending.for_employee(current_user).chronological.by_employee.paginate(page: params[:page]).per_page(5)

      today_date_range = DateRange.new(Date.today.to_date, Date.tomorrow.to_date)
      @pending_shifts_for_today = Shift.chronological.for_employee(current_user).for_dates(today_date_range).paginate(page: params[:page]).per_page(5)
    end

    # if params[:status] == 'upcoming'
    #   @shifts = @upcoming_shifts
    #   @state = 'upcoming'
    # elsif params[:status] == 'past'
    #   @shifts = @past_shifts
    #   @state = 'past'
    # end 


    

  end

  # GET /shifts/1
  # GET /shifts/1.json
  def show
    get_current_jobs_for_shift
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
    
  end

  # GET /shifts/1/edit
  def edit
  end

  # POST /shifts
  # POST /shifts.json
  def create
    @shift = Shift.new(shift_params)
    
    if @shift.save
      redirect_to shifts_path, notice: "Shift created for #{@shift.assignment.employee.proper_name} at #{@shift.assignment.store.name}."
    else
      render action: 'new'
    end
    
  end

  def clockin
      @time_clock1 = TimeClock.new(@shift)
      @time_clock1.start_shift_at(Time.now)
      @shift.reload
      @shift.status = 'started'
      redirect_to home_path, notice: "Shift for #{@shift.start_time.strftime( "%I:%M %p")} has begun"
  end


  def get_current_jobs_for_shift
      @current_jobs = ShiftJob.for_shift(@shift)
  end



  # PATCH/PUT /shifts/1
  # PATCH/PUT /shifts/1.json
  def update
    if @shift.update(shift_params)
      redirect_to home_path, notice: "#{@shift.assignment.employee.proper_name}'s shift at #{@shift.assignment.store.name} is updated."
    else
      render action: 'edit'
    end
  end

  # DELETE /shifts/1
  # DELETE /shifts/1.json
  def destroy
    @shift.destroy
    respond_to do |format|
      format.html { redirect_to shifts_url, notice: 'Shift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

  def clockout
      @time_clock2 = TimeClock.new(@shift)
      @time_clock2.end_shift_at(Time.now)
      @shift.reload
      @shift.status = 'finished'
      redirect_to home_path, notice: "Shift has been clocked out"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shift_params
      params.require(:shift).permit(:date, :start_time, :end_time, :notes, :status, :assignment_id)
    end

    
end

app/views/shifts/_all_shifts.html.erb
<%= render partial: 'shifts_lists', locals: { state: 'All', 
shifts: @all_shifts } %>

app/views/shifts/_fields.html.erb
<%= f.input :date, label_html: { class: 'active' } %>
<%= f.input :start_time, label_html: { class: 'active' } %>
<%= f.input :end_time, label_html: { class: 'active' } %>
<%= f.input :notes, label_html: { class: 'active'} %>
<%= f.input :status, collection: Shift::STATUS_LIST, include_blank: true %>

<%= f.input :assignment_id, collection: get_assignment_options, include_blank: true %>

app/views/shifts/_job_history.html.erb
  <div class="card">
    <div class="card-content">
      <h5>Current Jobs</h5>

      <table class="striped highlight">
        <thead>
        
          
        </thead>
        <% @current_jobs.each do |shift_job| %>
          <tr>
            <td><%= shift_job.job.name %></td>

          

            <td><%= link_to "Remove", shift_job, :method => :delete, data: { confirm: 'Are you sure you wish to delete this information?' },class: 'btn-small red darken-4'  %></td>
           
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
    </div>
    
  </div>
<% else %>
  <% if current_user.role?(:admin) || current_user.role?(:manager)%> 
  <div class="card grey lighten-3">
    <div class="card-action">
      <%= link_to "Add a new Job to this Shift", new_shift_job_path%>
    </div>
  </div>
  <%end%>

app/views/shifts/_past_shifts.html.erb
<%= render partial: 'shifts/shifts_lists', locals: { state: 'Past', 
shifts: @past_shifts, can_clock:false, is_past: true} %>

app/views/shifts/_shift_data.html.erb
<div class="card">
  <div class="card-content">
    <h4>Shift <%= @shift.id %> for <%= @shift.assignment.employee.proper_name%></h4>

        <p>Date:</p>
        
        <p><%=@shift.date%></p>
        <br>
        <p>Start Time:</p>
       
        <p><%=@shift.start_time.strftime("%I:%M %p")%></p>
        <br>
        <p>End Time:</p>
        <p><%=@shift.end_time.strftime("%I:%M %p")%></p>
        <br>
        <p>Notes:</p>
      
        <p><%=@shift.notes%></p>
        <br>

        <p>Shift Status:</p>
        <p><%=@shift.status%></p>
        

      

        

     

    
      <br>
  </div>
</div>

app/views/shifts/_shifts_lists.html.erb
<div class="card">
  <div class="card-content">
    <h5><%= state.capitalize %> Shifts</h5>

    <% if shifts.blank? %>
      <p>There are no <%= state.downcase %> shifts at this time.</p>
    <% else %>

      <table class="striped highlight">
        <thead>
          <tr>
            <th>Shift ID</th>
            <th>Assigned At</th>
            <th>Employee Name</th>
            <th>Date</th>

            <% if is_past == false%>
            <th>Start Time</th>
            <th>End Time</th>
            <%end%>
          
                       
          </tr>
        </thead>
        <tbody>
          <% shifts.each do |shift| %>
            <tr>

              <td class='hyperlink'><%= link_to shift.id, shift_path(shift)%></td>
              <%if current_user.role?(:admin)%>
                <td class='hyperlink'><%= link_to shift.assignment.store.name, store_path(shift.assignment.store)%></td>
              <%else%>
                <td><%= shift.assignment.store.name%></td>
              <%end%>
              
              <td class='hyperlink'><%= link_to shift.employee.name, employee_path(shift.assignment.employee) %></td>


              <td><%= shift.date.strftime("%-m/%-d/%y")%></td>

              <% if is_past == false%>
              <td><%=shift.start_time.strftime("%I:%M %p")%></td>
              <td><%=shift.end_time.strftime("%I:%M %p")%></td>
              <%end%>
                



               <% if current_user.role?(:admin) || current_user.role?(:manager) %>
                  <td>
                    <%= link_to(edit_shift_path(shift), class: 'btn-small cyan darken-4') do %>
                      &nbsp;Edit&nbsp;
                    <% end %>
                  </td>
              <% end %>


               <% if current_user.role?(:admin) || current_user.role?(:manager) %>
                  <td>
              <%= link_to(shift_path(shift), method: :delete, data: { confirm: 'Are you sure you wish to delete this shift?' }, class: 'btn-small red darken-4') do %>
                &nbsp;Delete&nbsp;

              <% end %>
              </td>

              

           <% end %>

                 


            <% if current_user.role?(:admin) || current_user.role?(:manager) %>

               <% if is_past %>
                  <td>
                      
                      <%= link_to(new_shift_job_path(shift_id: shift.id), class: 'btn-small blue darken-1') do %>
                        &nbsp;Add Job to Shift <%=shift.id%>&nbsp;

                  <% end %>

                  </td>
                 <td>
                    <ul class="collapsible">
                      <li>
                        <div class="collapsible-header"><i class="material-icons">add</i>View Jobs with this Shift</div>
                        <div class="collapsible-body">
                          
                                <table>
                                  <thead>
                                  </thead>

                                  <tbody>
                                    
                                      <% ShiftJob.for_shift(shift).each do |shift_job| %>
                                      <tr>
                                          <td><%=shift_job.job.name%></td>
                                          <td>
                                              <%= link_to(shift_job_path(shift_job), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }, class: 'btn-small red darken-4') do %>
                                                &nbsp;Delete&nbsp;

                                              <% end %>
                                          </td>
                                      <%end%>
                                      <tr>
                                    
                                  </tbody>
                                </table>
                        </div>
                      </li>
                      
                    </ul>
                 </td>
                <%end%>
                  


            <%end%>




          

               
            </tr>

           

            
        <% end %>
        </tbody>
      </table>
      <p class="supertiny"></p>
      <br />
      
      <%= will_paginate shifts, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
      <br />
   
    <% end %>
  </div>
</div>

app/views/shifts/_special_employee_shift_clock_view.html.erb
<div class="card">
  <div class="card-content">
    <h5><%= state.capitalize %> Shifts</h5>

    <% if shifts.blank? %>
      <p>There are no <%= state.downcase %> shifts at this time.</p>
    <% else %>

      <table class="striped highlight">
        <thead>
          <tr>
            <th>Employee Name</th>
            <th>Store Name</th>
            <th>Date</th>
            <th>Start Time</th>
            <th>End Time</th>
                       
          </tr>
        </thead>
        <tbody>
          <% shifts.each do |shift| %>
            <tr>

            <% if shift.status != 'finished'%>

              <td><%=shift.employee.name%></td>

              <%if current_user.role?(:admin)%>
                <td><%= link_to shift.assignment.store.name, store_path(shift.assignment.store) %></td>
              <%else%>
                <td><%= shift.assignment.store.name%></td>
              <%end%>
              <td><%= shift.date.strftime("%-m/%-d/%y")%></td>
              <td><%=shift.start_time.strftime("%I:%M %p")%></td>
              <td><%=shift.end_time.strftime("%I:%M %p")%></td>
                

                <% if current_user.role?(:admin) || current_user.role?(:manager) %>
                  <td>
                      
                      <%= link_to(new_shift_path, class: 'btn-small green darken-1') do %>
                        &nbsp;Add&nbsp;

                  <% end %>
                  </td>
              <% end %>


               <% if current_user.role?(:admin) || current_user.role?(:manager) %>
                  <td>
                    <%= link_to(edit_shift_path(shift), class: 'btn-small cyan darken-4') do %>
                      &nbsp;Edit&nbsp;
                    <% end %>
                  </td>
              <% end %>


               <% if current_user.role?(:admin) || current_user.role?(:manager) %>
                  <td>
              <%= link_to(shift_path(shift), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }, class: 'btn-small red darken-4') do %>
                &nbsp;Delete&nbsp;

              <% end %>
              </td>

           <% end %>

                  <td>
                      
                      <%= link_to(shift_path(shift), class: 'btn-small black darken-1') do %>
                        &nbsp;View Shift &nbsp;

                  <% end %>
                  </td>




           

            <% if can_clock %>

            
              <%if Time.now.strftime( "%H%M%S%N" ) <= shift.end_time.strftime( "%H%M%S%N" )%>     
              <td>
                
                <%= link_to(clock_in_shift_path(shift), method: :patch, data: { confirm: 'Are you sure you wish to clock in this shift?' }, class: 'btn-small orange darken-3') do %>
                  &nbsp;Clock in&nbsp;
                <% end %>
             
              </td>

              <% end %>
              

              <%if Time.now.strftime( "%H%M%S%N" ) > shift.end_time.strftime( "%H%M%S%N" )%>
              <td>

                
                <%= link_to(clock_out_shift_path(shift), method: :patch, data: { confirm: 'Are you sure you wish to clock out this shift?' }, class: 'btn-small pink darken-1') do %>
                  &nbsp;Clock out &nbsp;
                <% end %>
             
              </td>

              <% end %>
            
            <% end %>

          

            <%end%>   
            </tr>

           

            
        <% end %>
        </tbody>
      </table>
      <p class="supertiny"></p>
      <br />
      
      <%= will_paginate shifts, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
      <br />
   
    <% end %>
  </div>
</div>

app/views/shifts/_tabbed_index.html.erb
<div id='tabbed'>
  <div class="row">
    <div class="col s12">
      <ul class="tabs">
      	<li class="tab col s3"><a href="#test1">Upcoming/Current Shifts</a></li>
        <li class="tab col s3"><a href="#test2">Past/Completed Shifts</a></li>
        
        
      </ul>
    </div>
    <div id="test1" class="col s12"><%= render :partial => "shifts/upcoming_shifts" %> </div>
    <div id="test2" class="col s12"><%= render :partial => "shifts/past_shifts" %> </div>
    
  </ul>


    
	</div>
   
    
</div>




<% if current_user.role?(:admin) || current_user.role?(:manager)%>
  <%= render :partial => "partials/add_new_object", locals: {model_name: 'shift'} %>
<% end %>

app/views/shifts/_upcoming_shifts.html.erb
<%= render partial: 'shifts/shifts_lists', locals: { state: 'Upcoming', 
shifts: @upcoming_shifts, can_clock: false, is_past:false} %>

app/views/shifts/edit.html.erb
<%= render partial: 'partials/form_structure', locals: {object: @shift, 
                                                        type_of_form: 'Shift',
                                                        fields: 'fields'} %>

app/views/shifts/index.html.erb
<%= render partial: 'tabbed_index' %>

app/views/shifts/new.html.erb
<%= render partial: 'partials/form_structure', locals: {object: @shift, 
                                                        type_of_form: 'New Shift',
                                                        fields: 'fields'} %>

app/views/shifts/show.html.erb
<%= render partial: 'partials/show_structure', locals: {model_name: 'shift', 
                                                         object: @shift,
                                                         primary: 'shift_data', 
                                                         secondary: nil,
                                                         sidebar: 'job_history',
                                                     	 sidebar2: nil} %>